"""update reports and reports_file tables

Revision ID: 24f00345b2ab
Revises: 091d3116331b
Create Date: 2025-10-22 12:57:06.242346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24f00345b2ab'
down_revision: Union[str, Sequence[str], None] = '091d3116331b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_file', sa.String(length=255), nullable=False),
    sa.Column('path_storage', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_files_id'), 'report_files', ['id'], unique=False)
    op.drop_index(op.f('ix_reports_file_id'), table_name='reports_file')
    op.drop_table('reports_file')
    op.add_column('reports', sa.Column('proposal', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('note', sa.Text(), nullable=True))
    op.alter_column('reports', 'major',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('reports', 'position',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_column('reports', 'suggestions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('suggestions', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('reports', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('reports', 'position',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('reports', 'major',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('reports', 'note')
    op.drop_column('reports', 'proposal')
    op.create_table('reports_file',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name_file', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('path_storage', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('report_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('reports_file_report_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reports_file_pkey'))
    )
    op.create_index(op.f('ix_reports_file_id'), 'reports_file', ['id'], unique=False)
    op.drop_index(op.f('ix_report_files_id'), table_name='report_files')
    op.drop_table('report_files')
    # ### end Alembic commands ###
