"""update reports and reports_file tables

Revision ID: 61056dad6670
Revises: 24f00345b2ab
Create Date: 2025-10-22 13:18:41.148176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61056dad6670'
down_revision: Union[str, Sequence[str], None] = '24f00345b2ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='reportstatus'),
               type_=sa.Enum('pending', 'completed', 'plagiarized', name='reportstatus', native_enum=False),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'status',
               existing_type=sa.Enum('pending', 'completed', 'plagiarized', name='reportstatus', native_enum=False),
               type_=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='reportstatus'),
               nullable=True)
    # ### end Alembic commands ###
