"""add raw_content column to report

Revision ID: 76bfcf9f3b4d
Revises: 61056dad6670
Create Date: 2025-10-24 15:46:40.767918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76bfcf9f3b4d'
down_revision: Union[str, Sequence[str], None] = '61056dad6670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('raw_content', sa.Text(), nullable=True, comment='Nội dung báo cáo công việc thô, dùng cho kiểm tra đạo văn'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'raw_content')
    # ### end Alembic commands ###
