"""add company column to reports

Revision ID: 7f6d5d896da4
Revises: 76bfcf9f3b4d
Create Date: 2025-11-09 17:50:01.443166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f6d5d896da4'
down_revision: Union[str, Sequence[str], None] = '76bfcf9f3b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('company', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'company')
    # ### end Alembic commands ###
